version: 0.0
os: linux
files:
   - source: /
     destination: /home/ubuntu/test/
permissions:
   - object: /home/ubuntu/test/
     pattern: "**"
     owner: ubuntu
     group: ubuntu
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
   AfterInstall:
